{
  "namespace": "CarrierControllerSlaveState",
  "name": "main",
  "type": "record",
  "fields": [
    {
      "name": "deviceId",
      "doc": "Hostname of the sending device (RevPi), e.g. \"ivtp20\".",
      "type": "string"
    },
    {
      "name": "sortingUnitKey",
      "doc": "The sorting unit key, e.g. \"P_VET_01\" for RPZ Vetroz.",
      "type": "string"
    },
    {
      "name": "timestamp",
      "doc": "Message timestamp. ISO 8601 Format, e.g. 2025-06-20T17:00:00+02:00.",
      "type": "string"
    },
    {
      "name": "serialNumber",
      "doc": "The serial number of the carrier.",
      "type": "string"
    },
    {
      "name": "groupId",
      "doc": "The group id of the carrier.",
      "type": "int"
    },
    {
      "name": "carrierId",
      "doc": "The carrier id.",
      "type": "int"
    },
    {
      "name": "state",
      "doc": "The current state of the carrier controller slave.",
      "type": "string"
    },
    {
      "name": "upTime",
      "doc": "Total runtime of the CCS since last boot in seconds.",
      "type": "int"
    },
    {
      "name": "dcBusVoltage",
      "doc": "DC bus voltage in volt.",
      "type": "double"
    },
    {
      "name": "temperature",
      "doc": "Temperature in the controller in degrees Celsius.",
      "type": "double"
    },
    {
      "name": "connected",
      "doc": "True, if updates have been received from the CCM within the last 60 seconds.",
      "type": "boolean"
    },
    {
      "name": "errors",
      "doc": "Errors received from the CCS.",
      "type": {
        "type": "array",
        "items": {
          "name": "errors",
          "doc": "",
          "type": "string"
        }
      }
    }
  ]
}