{
  "namespace": "CarrierAccelerationEvent",
  "name": "main",
  "type": "record",
  "fields": [
    {
      "name": "deviceId",
      "doc": "Hostname of the sending device (RevPi), e.g. \"ivtp20\".",
      "type": "string"
    },
    {
      "name": "sortingUnitKey",
      "doc": "The sorting unit key, e.g. \"P_VET_01\" for RPZ Vetroz",
      "type": "string"
    },
    {
      "name": "timestamp",
      "doc": "Message timestamp. ISO 8601 Format, e.g. 2025-06-20T17:00:00+02:00.",
      "type": "string"
    },
    {
      "name": "groupId",
      "doc": "The group id of the carrier.",
      "type": "int"
    },
    {
      "name": "carrierId",
      "doc": "The carrier id.",
      "type": "int"
    },
    {
      "name": "position",
      "doc": "The position in meter of the CCM on the sorting unit.",
      "type": "double"
    },
    {
      "name": "sensorId",
      "doc": "The sensor id of the acceleration sensor.",
      "type": "int"
    },
    {
      "name": "accelerationX",
      "doc": "X-axis acceleration in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationY",
      "doc": "Y-axis acceleration in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationZ",
      "doc": "Z-axis acceleration in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationXMin",
      "doc": "X-axis acceleration minimum in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationYMin",
      "doc": "Y-axis acceleration minimum in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationZMin",
      "doc": "Z-axis acceleration minimum in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationXMax",
      "doc": "X-axis acceleration maximum in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationYMax",
      "doc": "Y-axis acceleration maximum in m/s^2.",
      "type": "double"
    },
    {
      "name": "accelerationZMax",
      "doc": "Z-axis acceleration maximum in m/s^2.",
      "type": "double"
    },
    {
      "name": "sorterSpeed",
      "doc": "The current sorter speed in m/s.",
      "type": "double"
    },
    {
      "name": "connected",
      "doc": "True, if updates have been received from the CCM within the last 60 seconds.",
      "type": "boolean"
    }
  ]
}