{
  "namespace": "CarrierChainForceEvent",
  "name": "main",
  "type": "record",
  "fields": [
    {
      "name": "deviceId",
      "doc": "MAC address of the sending device, e.g. 2EC8957302CA",
      "type": "string"
    },
    {
      "name": "sortingCenter",
      "doc": "The sorting center id, e.g. \"HRK\" for BPZ Härkingen\r\nTODO Use sortingLocationKey instead -> clarify with jeanrichardm",
      "type": "string"
    },
    {
      "name": "sorterNumber",
      "doc": "The sorter number (unique for the sorting center).\r\nTODO Use sortingUnitKey & sorterKey instead -> clarify with jeanrichardm",
      "type": "int"
    },
    {
      "name": "timestamp",
      "doc": "Message timestamp. ISO 8601 Format, e.g. 2025-06-20T17:00:00+02:00",
      "type": "string"
    },
    {
      "name": "group",
      "doc": "The group id of the carrier.",
      "type": "int"
    },
    {
      "name": "carrier",
      "doc": "The carrier id.",
      "type": "int"
    },
    {
      "name": "position",
      "doc": "The position in mm of the CCM on the sorting unit.",
      "type": "int"
    },
    {
      "name": "sensorId",
      "doc": "The sensor id of the acceleration sensor.",
      "type": "int"
    },
    {
      "name": "force",
      "doc": "Force in Newton measured by the chain force sensor.",
      "type": "int"
    }
  ]
}