{
  "namespace": "PowerAnalyzerEvent",
  "name": "main",
  "type": "record",
  "fields": [
    {
      "name": "deviceId",
      "doc": "MAC address of the sending device, e.g. 2EC8957302CA",
      "type": "string"
    },
    {
      "name": "sortingCenter",
      "doc": "The sorting center id, e.g. \"HRK\" for BPZ Härkingen\r\nTODO Use sortingLocationKey instead -> clarify with jeanrichardm",
      "type": "string"
    },
    {
      "name": "sorterNumber",
      "doc": "The sorter number (unique for the sorting center).\r\nTODO Use sortingUnitKey & sorterKey instead -> clarify with jeanrichardm",
      "type": "int"
    },
    {
      "name": "timestamp",
      "doc": "Message timestamp. ISO 8601 Format, e.g. 2025-06-20T17:00:00+02:00",
      "type": "string"
    },
    {
      "name": "group",
      "doc": "The group id of the carrier.",
      "type": "int"
    },
    {
      "name": "carrier",
      "doc": "The carrier id.",
      "type": "int"
    },
    {
      "name": "unitId",
      "doc": "The unit id of the power analyzer.",
      "type": "int"
    },
    {
      "name": "voltageL1N",
      "doc": "Power analyzer metrics. \n V, 19000",
      "type": "double"
    },
    {
      "name": "voltageL2N",
      "doc": "V, 19002",
      "type": "double"
    },
    {
      "name": "voltageL3N",
      "doc": "V, 19004",
      "type": "double"
    },
    {
      "name": "currentIL1",
      "doc": "A, 19012",
      "type": "double"
    },
    {
      "name": "currentIL2",
      "doc": "A, 19014",
      "type": "double"
    },
    {
      "name": "currentIL3",
      "doc": "A, 19016",
      "type": "double"
    },
    {
      "name": "currentSum",
      "doc": "A, 19018",
      "type": "double"
    },
    {
      "name": "realPowerP1L1N",
      "doc": "W, 19020",
      "type": "double"
    },
    {
      "name": "realPowerP2L2N",
      "doc": "W, 19022",
      "type": "double"
    },
    {
      "name": "realPowerP3L3N",
      "doc": "W, 19024",
      "type": "double"
    },
    {
      "name": "realPowerSum",
      "doc": "W, 19026",
      "type": "double"
    },
    {
      "name": "apparentPowerS1L1N",
      "doc": "VA, 19028",
      "type": "double"
    },
    {
      "name": "apparentPowerS2L2N",
      "doc": "VA, 19030",
      "type": "double"
    },
    {
      "name": "apparentPowerS3L3N",
      "doc": "VA, 19032",
      "type": "double"
    },
    {
      "name": "apparentPowerSum",
      "doc": "VA, 19034",
      "type": "double"
    },
    {
      "name": "reactivePowerQ1L1N",
      "doc": "var, 19036",
      "type": "double"
    },
    {
      "name": "reactivePowerQ2L2N",
      "doc": "var, 19038    ",
      "type": "double"
    },
    {
      "name": "reactivePowerQ3L3N",
      "doc": "var, 19040",
      "type": "double"
    },
    {
      "name": "reactivePowerSum",
      "doc": "var, 19042",
      "type": "double"
    },
    {
      "name": "realEnergyL1",
      "doc": "Wh, 19054",
      "type": "double"
    },
    {
      "name": "realEnergyL2",
      "doc": "Wh, 19056",
      "type": "double"
    },
    {
      "name": "realEnergyL3",
      "doc": "Wh, 19058",
      "type": "double"
    },
    {
      "name": "realEnergySum",
      "doc": "Wh 19060",
      "type": "double"
    },
    {
      "name": "apparentEnergyL1",
      "doc": "VAh, 19078",
      "type": "double"
    },
    {
      "name": "apparentEnergyL2",
      "doc": "VAh, 19080",
      "type": "double"
    },
    {
      "name": "apparentEnergyL3",
      "doc": "VAh, 19082",
      "type": "double"
    },
    {
      "name": "apparentEnergySum",
      "doc": "VAh, 19084",
      "type": "double"
    },
    {
      "name": "reactiveEnergyL1",
      "doc": "varh, 19086",
      "type": "double"
    },
    {
      "name": "reactiveEnergyL2",
      "doc": "varh, 19088",
      "type": "double"
    },
    {
      "name": "reactiveEnergyL3",
      "doc": "varh, 19090",
      "type": "double"
    },
    {
      "name": "reactiveEnergySum",
      "doc": "varh, 19092",
      "type": "double"
    }
  ]
}